techpack: camera-bengal/wl2866d: Fix error cause a function declaration is deprecated
Fixes:
../techpack/camera-bengal/drivers/wl2866d/wl2866d.c:139:30: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  139 | static void enable_i2c_pullup()
      |                              ^
      |                               void
1 error generated.

Change-Id: I59bb9ac250081c13c694deb84233a81851a892db